### ISSUE TITLE
not install any resources

### ISSUE THREAD

**Issue by neochapay** [nemomobile/lipstick-colorful-home#1]
when i write make install make only copy bin file but not install qml and images

**Comment by rburchell** [comment]
that's because they're embedded into the binary, using Qt's resource system.

**Comment by Venemo** [comment]
I've also replied on twitter: https://twitter.com/Venemo/status/238626674676228099

**Comment by neochapay** [comment]
it`s not good...
must been more comfigureable :)

**Comment by rburchell** [comment]
there is no need to make the source configurable or installable. there is one trick which we use elsewhere in Nemo which I also plan on adding sometime, though - support for running from local file-copied QML (useful for quick iterations of design without rebuilds)
