### ISSUE TITLE
Black screen after run

### ISSUE THREAD

**Issue by neochapay** [nemomobile/lipstick-colorful-home#2]
in console i have

qrc:/qml/pages/AppLauncher.qml:40:5: QML GridView: Binding loop detected for property "height"
loaded the Generic plugin 
qrc:/qml/pages/AppLauncher/LauncherItem.qml:32:5: QML Image: Cannot open file:///: Path is a directory
qrc:/qml/pages/AppLauncher/LauncherItem.qml:32:5: QML Image: Cannot open file:///: Path is a directory
qrc:/qml/pages/AppLauncher/LauncherItem.qml:32:5: QML Image: Cannot open file:///: Path is a directory
qrc:/qml/pages/AppLauncher/LauncherItem.qml:32:5: QML Image: Cannot open file:///: Path is a directory
qrc:/qml/pages/AppLauncher/LauncherItem.qml:32:5: QML Image: Cannot open file:///: Path is a directory
qrc:/qml/pages/AppLauncher/LauncherItem.qml:32:5: QML Image: Cannot open file:///: Path is a directory
qrc:/qml/pages/AppLauncher/LauncherItem.qml:32:5: QML Image: Cannot open file:///: Path is a directory
qrc:/qml/pages/AppLauncher/LauncherItem.qml:32:5: QML Image: Cannot open file:///: Path is a directory
qrc:/qml/pages/AppLauncher/LauncherItem.qml:32:5: QML Image: Cannot open file:///: Path is a directory
qrc:/qml/pages/AppLauncher/LauncherItem.qml:32:5: QML Image: Cannot open file:///: Path is a directory
qrc:/qml/pages/AppLauncher/LauncherItem.qml:32:5: QML Image: Cannot open file:///: Path is a directory
qrc:/qml/pages/AppLauncher/LauncherItem.qml:32:5: QML Image: Cannot open file:///: Path is a directory
qrc:/qml/pages/AppLauncher/LauncherItem.qml:32:5: QML Image: Cannot open file:///: Path is a directory
qrc:/qml/pages/AppLauncher/LauncherItem.qml:32:5: QML Image: Cannot open file:///: Path is a directory
qrc:/qml/pages/AppLauncher/LauncherItem.qml:32:5: QML Image: Cannot open file:///: Path is a directory
qrc:/qml/pages/AppLauncher/LauncherItem.qml:32:5: QML Image: Cannot open file:///: Path is a directory
qrc:/qml/pages/AppLauncher/LauncherItem.qml:32:5: QML Image: Cannot open file:///: Path is a directory
qrc:/qml/pages/AppLauncher/LauncherItem.qml:32:5: QML Image: Cannot open file:///: Path is a directory
qrc:/qml/pages/AppLauncher/LauncherItem.qml:32:5: QML Image: Cannot open file:///: Path is a directory
qrc:/qml/pages/AppLauncher/LauncherItem.qml:32:5: QML Image: Cannot open file:///: Path is a directory
qrc:/qml/pages/AppLauncher/LauncherItem.qml:32:5: QML Image: Cannot open file:///: Path is a directory
qrc:/qml/pages/AppLauncher/LauncherItem.qml:32:5: QML Image: Cannot open file:///: Path is a directory
qrc:/qml/pages/AppLauncher/LauncherItem.qml:32:5: QML Image: Cannot open file:///: Path is a directory
qrc:/qml/pages/AppLauncher/LauncherItem.qml:32:5: QML Image: Cannot open file:///: Path is a directory
qrc:/qml/pages/AppLauncher/LauncherItem.qml:32:5: QML Image: Cannot open file:///: Path is a directory
qrc:/qml/pages/AppLauncher/LauncherItem.qml:32:5: QML Image: Cannot open file:///: Path is a directory
qrc:/qml/pages/AppLauncher/LauncherItem.qml:32:5: QML Image: Cannot open file:///: Path is a directory
qrc:/qml/pages/AppLauncher/LauncherItem.qml:32:5: QML Image: Cannot open file:///: Path is a directory
qrc:/qml/pages/AppLauncher/LauncherItem.qml:32:5: QML Image: Cannot open file:///: Path is a directory
qrc:/qml/pages/AppLauncher/LauncherItem.qml:32:5: QML Image: Cannot open file:///: Path is a directory
qrc:/qml/pages/AppLauncher/LauncherItem.qml:32:5: QML Image: Cannot open file:///: Path is a directory
qrc:/qml/pages/AppLauncher/LauncherItem.qml:32:5: QML Image: Cannot open file:///: Path is a directory
qrc:/qml/pages/AppLauncher/LauncherItem.qml:32:5: QML Image: Cannot open file:///: Path is a directory
qrc:/qml/pages/AppLauncher/LauncherItem.qml:32:5: QML Image: Cannot open file:///: Path is a directory
qrc:/qml/pages/AppLauncher/LauncherItem.qml:32:5: QML Image: Cannot open file:///: Path is a directory
qrc:/qml/pages/AppLauncher/LauncherItem.qml:32:5: QML Image: Cannot open file:///: Path is a directory
qrc:/qml/pages/AppLauncher/LauncherItem.qml:32:5: QML Image: Cannot open file:///: Path is a directory
qrc:/qml/pages/AppLauncher/LauncherItem.qml:32:5: QML Image: Cannot open file:///: Path is a directory
qrc:/qml/pages/AppLauncher/LauncherItem.qml:32:5: QML Image: Cannot open file:///: Path is a directory
qrc:/qml/pages/AppLauncher/LauncherItem.qml:32:5: QML Image: Cannot open file:///: Path is a directory
qrc:/qml/pages/AppLauncher/LauncherItem.qml:32:5: QML Image: Cannot open file:///: Path is a directory
qrc:/qml/pages/AppLauncher/LauncherItem.qml:32:5: QML Image: Cannot open file:///: Path is a directory
qrc:/qml/pages/AppLauncher/LauncherItem.qml:32:5: QML Image: Cannot open file:///: Path is a directory
qrc:/qml/pages/AppLauncher/LauncherItem.qml:32:5: QML Image: Cannot open file:///: Path is a directory
qrc:/qml/pages/AppLauncher/LauncherItem.qml:32:5: QML Image: Cannot open file:///: Path is a directory
qrc:/qml/pages/AppLauncher/LauncherItem.qml:32:5: QML Image: Cannot open file:///: Path is a directory
qrc:/qml/pages/AppLauncher/LauncherItem.qml:32:5: QML Image: Cannot open file:///: Path is a directory
qrc:/qml/pages/AppLauncher/LauncherItem.qml:32:5: QML Image: Cannot open file:///: Path is a directory
qrc:/qml/pages/AppLauncher/LauncherItem.qml:32:5: QML Image: Cannot open file:///: Path is a directory
qrc:/qml/pages/AppLauncher/LauncherItem.qml:32:5: QML Image: Cannot open file:///: Path is a directory
qrc:/qml/pages/AppLauncher/LauncherItem.qml:32:5: QML Image: Cannot open file:///: Path is a directory
qrc:/qml/pages/AppLauncher/LauncherItem.qml:32:5: QML Image: Cannot open file:///: Path is a directory
qrc:/qml/pages/AppLauncher/LauncherItem.qml:32:5: QML Image: Cannot open file:///: Path is a directory
qrc:/qml/pages/AppLauncher/LauncherItem.qml:32:5: QML Image: Cannot open file:///: Path is a directory
qrc:/qml/pages/AppLauncher/LauncherItem.qml:32:5: QML Image: Cannot open file:///: Path is a directory
qrc:/qml/pages/AppLauncher/LauncherItem.qml:32:5: QML Image: Cannot open file:///: Path is a directory
qrc:/qml/pages/AppLauncher/LauncherItem.qml:32:5: QML Image: Cannot open file:///: Path is a directory
qrc:/qml/pages/AppLauncher/LauncherItem.qml:32:5: QML Image: Cannot open file:///: Path is a directory
qrc:/qml/pages/AppLauncher/LauncherItem.qml:32:5: QML Image: Cannot open file:///: Path is a directory
qrc:/qml/pages/AppLauncher/LauncherItem.qml:32:5: QML Image: Cannot open file:///: Path is a directory
qrc:/qml/pages/AppLauncher/LauncherItem.qml:32:5: QML Image: Cannot open file:///: Path is a directory
qrc:/qml/pages/AppLauncher/LauncherItem.qml:32:5: QML Image: Cannot open file:///: Path is a directory
qrc:/qml/pages/AppLauncher/LauncherItem.qml:32:5: QML Image: Cannot open file:///: Path is a directory
qrc:/qml/pages/AppLauncher/LauncherItem.qml:32:5: QML Image: Cannot open file:///: Path is a directory
qrc:/qml/pages/AppLauncher/LauncherItem.qml:32:5: QML Image: Cannot open file:///: Path is a directory
qrc:/qml/pages/AppLauncher/LauncherItem.qml:32:5: QML Image: Cannot open file:///: Path is a directory
qrc:/qml/pages/AppLauncher/LauncherItem.qml:32:5: QML Image: Cannot open file:///: Path is a directory
qrc:/qml/pages/AppLauncher/LauncherItem.qml:32:5: QML Image: Cannot open file:///: Path is a directory
qrc:/qml/pages/AppLauncher/LauncherItem.qml:32:5: QML Image: Cannot open file:///: Path is a directory
qrc:/qml/pages/AppLauncher/LauncherItem.qml:32:5: QML Image: Cannot open file:///: Path is a directory
qrc:/qml/pages/AppLauncher/LauncherItem.qml:32:5: QML Image: Cannot open file:///: Path is a directory
qrc:/qml/pages/AppLauncher/LauncherItem.qml:32:5: QML Image: Cannot open file:///: Path is a directory
qrc:/qml/pages/AppLauncher/LauncherItem.qml:32:5: QML Image: Cannot open file:///: Path is a directory
qrc:/qml/pages/AppLauncher/LauncherItem.qml:32:5: QML Image: Cannot open file:///: Path is a directory
qrc:/qml/pages/AppLauncher/LauncherItem.qml:32:5: QML Image: Cannot open file:///: Path is a directory
qrc:/qml/pages/AppLauncher/LauncherItem.qml:32:5: QML Image: Cannot open file:///: Path is a directory
qrc:/qml/pages/AppLauncher/LauncherItem.qml:32:5: QML Image: Cannot open file:///: Path is a directory
qrc:/qml/pages/AppLauncher/LauncherItem.qml:32:5: QML Image: Cannot open file:///: Path is a directory
qrc:/qml/pages/AppLauncher/LauncherItem.qml:32:5: QML Image: Cannot open file:///: Path is a directory
qrc:/qml/pages/AppLauncher/LauncherItem.qml:32:5: QML Image: Cannot open file:///: Path is a directory
qrc:/qml/pages/AppLauncher/LauncherItem.qml:32:5: QML Image: Cannot open file:///: Path is a directory
qrc:/qml/pages/AppLauncher/LauncherItem.qml:32:5: QML Image: Cannot open file:///: Path is a directory
qrc:/qml/pages/AppLauncher/LauncherItem.qml:32:5: QML Image: Cannot open file:///: Path is a directory
qrc:/qml/pages/AppLauncher/LauncherItem.qml:32:5: QML Image: Cannot open file:///: Path is a directory
qrc:/qml/pages/AppLauncher/LauncherItem.qml:32:5: QML Image: Cannot open file:///: Path is a directory
qrc:/qml/pages/AppLauncher/LauncherItem.qml:32:5: QML Image: Cannot open file:///: Path is a directory
qrc:/qml/pages/AppLauncher/LauncherItem.qml:32:5: QML Image: Cannot open file:///: Path is a directory
qrc:/qml/pages/AppLauncher/LauncherItem.qml:32:5: QML Image: Cannot open file:///: Path is a directory
qrc:/qml/pages/AppLauncher/LauncherItem.qml:32:5: QML Image: Cannot open file:///: Path is a directory
qrc:/qml/pages/AppLauncher/LauncherItem.qml:32:5: QML Image: Cannot open file:///: Path is a directory
qrc:/qml/pages/AppLauncher/LauncherItem.qml:32:5: QML Image: Cannot open file:///: Path is a directory
qrc:/qml/pages/AppLauncher/LauncherItem.qml:32:5: QML Image: Cannot open file:///: Path is a directory
qrc:/qml/pages/AppLauncher/LauncherItem.qml:32:5: QML Image: Cannot open: file:///usr/share/pixmaps//seahorse

And black screen as result

**Comment by Venemo** [comment]
The messages and the black screen are unrelated.

The messages are not any actual issue, they only indicate that some application icons failed to load (due to non-existent images or incorrect settings), in which case it will fallback to using a default picture which is embedded in the executable.

You forgot to add a few details:
- Did you build latest master from git?
- What operating system are you trying to use it on?
- What compositor are you running?

**Comment by saukko** [comment]
I reported similar bug to bugzilla yesterday https://bugs.nemomobile.org/show_bug.cgi?id=401

**Comment by rburchell** [comment]
presumably fixed in latest
